# Generated by Django 4.2.2 on 2025-09-20 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpdinterFornecedor',
            fields=[
                ('for_cnpj', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('for_nm_fornecedor', models.CharField(max_length=70)),
                ('for_flag_multifilial', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CPDINTER_FORNECEDOR',
            },
        ),
        migrations.CreateModel(
            name='CpdinterNotasFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_id_sequencial', models.IntegerField()),
                ('for_desc_nota', models.CharField(max_length=512)),
                ('for_cd_loja', models.IntegerField()),
                ('for_dia_vencimento', models.IntegerField()),
                ('for_dia_entrega', models.IntegerField()),
                ('for_cnpj', models.ForeignKey(db_column='for_cnpj', on_delete=django.db.models.deletion.DO_NOTHING, to='CPDINTER.cpdinterfornecedor')),
            ],
            options={
                'db_table': 'CPDINTER_NOTAS_FORNECEDOR',
                'unique_together': {('for_cnpj', 'for_id_sequencial')},
            },
        ),
        migrations.CreateModel(
            name='CpdinterNotasMensaisForn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_id_sequencial', models.IntegerField()),
                ('for_nr_nota', models.BigIntegerField()),
                ('for_vl_nota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('for_dt_entrega', models.DateField(blank=True, null=True)),
                ('for_dt_emissao', models.DateField(blank=True, null=True)),
                ('for_dt_vencimento', models.DateField(blank=True, null=True)),
                ('for_dt_envio_cadastro', models.DateField(blank=True, null=True)),
                ('for_dt_envio_financ', models.DateField(blank=True, null=True)),
                ('for_tx_observacao', models.CharField(blank=True, max_length=512, null=True)),
                ('for_cnpj', models.ForeignKey(db_column='for_cnpj', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_mensais', to='CPDINTER.cpdinternotasfornecedor')),
            ],
        ),
    ]
